language: ruby
os: linux
dist: bionic
cache: bundler
services:
  - docker
jobs:
  include:
    - name: "Cookstyle"
      script:
        - bundle exec cookstyle -f fuubar
    - name: "Test Kitchen (accounts)"
      script:
        - bundle exec kitchen test accounts-ubuntu-1804
    - name: "Test Kitchen (apache)"
      script:
        - bundle exec kitchen test apache-ubuntu-1804
    - name: "Test Kitchen (apt)"
      script:
        - bundle exec kitchen test apt-ubuntu-1804
    - name: "Test Kitchen (bind)"
      script:
        - bundle exec kitchen test bind-ubuntu-1804
    - name: "Test Kitchen (blogs)"
      script:
        - bundle exec kitchen test blogs-ubuntu-1804
    - name: "Test Kitchen (civicrm)"
      script:
        - bundle exec kitchen test civicrm-ubuntu-1804
    - name: "Test Kitchen (clamav)"
      script:
        - bundle exec kitchen test clamav-ubuntu-1804
    - name: "Test Kitchen (devices)"
      script:
        - bundle exec kitchen test devices-ubuntu-1804
    - name: "Test Kitchen (dhcpd)"
      script:
        - bundle exec kitchen test dhcpd-ubuntu-1804
    - name: "Test Kitchen (dmca)"
      script:
        - bundle exec kitchen test dmca-ubuntu-1804
    - name: "Test Kitchen (donate)"
      script:
        - bundle exec kitchen test donate-ubuntu-1804
    - name: "Test Kitchen (exim)"
      script:
        - bundle exec kitchen test exim-ubuntu-1804
    - name: "Test Kitchen (fail2ban)"
      script:
        - bundle exec kitchen test fail2ban-ubuntu-1804
    - name: "Test Kitchen (forum)"
      script:
        - bundle exec kitchen test forum-ubuntu-1804
    - name: "Test Kitchen (ftp)"
      script:
        - bundle exec kitchen test ftp-ubuntu-1804
    - name: "Test Kitchen (geodns)"
      script:
        - bundle exec kitchen test geodns-ubuntu-1804
    - name: "Test Kitchen (geoipupdate)"
      script:
        - bundle exec kitchen test geoipupdate-ubuntu-1804
    - name: "Test Kitchen (gps-tile)"
      script:
        - bundle exec kitchen test gps-tile-ubuntu-1804
    - name: "Test Kitchen (hardare)"
      script:
        - bundle exec kitchen test hardware-ubuntu-1804
    - name: "Test Kitchen (incron)"
      script:
        - bundle exec kitchen test incron-ubuntu-1804
    - name: "Test Kitchen (letsencrypt)"
      script:
        - bundle exec kitchen test letsencrypt-ubuntu-1804
    - name: "Test Kitchen (mailman)"
      script:
        - bundle exec kitchen test mailman-ubuntu-1804
    - name: "Test Kitchen (memcached)"
      script:
        - bundle exec kitchen test memcached-ubuntu-1804
    - name: "Test Kitchen (munin)"
      script:
        - bundle exec kitchen test munin-ubuntu-1804
    - name: "Test Kitchen (munin::plugins)"
      script:
        - bundle exec kitchen test munin-plugins-ubuntu-1804
    - name: "Test Kitchen (munin::server)"
      script:
        - bundle exec kitchen test munin-server-ubuntu-1804
    - name: "Test Kitchen (mysql)"
      script:
        - bundle exec kitchen test mysql-ubuntu-1804
    - name: "Test Kitchen (networking)"
      script:
        - bundle exec kitchen test networking-ubuntu-1804
    - name: "Test Kitchen (nginx)"
      script:
        - bundle exec kitchen test nginx-ubuntu-1804
    - name: "Test Kitchen (nodejs)"
      script:
        - bundle exec kitchen test nodejs-ubuntu-1804
    - name: "Test Kitchen (ntp)"
      script:
        - bundle exec kitchen test ntp-ubuntu-1804
    - name: "Test Kitchen (openssh)"
      script:
        - bundle exec kitchen test openssh-ubuntu-1804
    - name: "Test Kitchen (osmosis)"
      script:
        - bundle exec kitchen test osmosis-ubuntu-1804
    - name: "Test Kitchen (osqa)"
      script:
        - bundle exec kitchen test osqa-ubuntu-1804
      attributes:
        osqa:
          sites:
            - name: help.example.com
    - name: "Test Kitchen (otrs)"
      script:
        - bundle exec kitchen test otrs-ubuntu-1804
    - name: "Test Kitchen (passenger)"
      script:
        - bundle exec kitchen test passenger-ubuntu-1804
    - name: "Test Kitchen (piwik)"
      script:
        - bundle exec kitchen test piwik-ubuntu-1804
    - name: "Test Kitchen (planet)"
      script:
        - bundle exec kitchen test planet-ubuntu-1804
    - name: "Test Kitchen (planet::dump)"
      script:
        - bundle exec kitchen test planet-dump-ubuntu-1804
    - name: "Test Kitchen (planet::notes)"
      script:
        - bundle exec kitchen test planet-notes-ubuntu-1804
    - name: "Test Kitchen (planet::replication)"
      script:
        - bundle exec kitchen test planet-replication-ubuntu-1804
    - name: "Test Kitchen (postgresql)"
      script:
        - bundle exec kitchen test postgresql-ubuntu-1804
    - name: "Test Kitchen (python)"
      script:
        - bundle exec kitchen test python-ubuntu-1804
    - name: "Test Kitchen (rsyncd)"
      script:
        - bundle exec kitchen test rsyncd-ubuntu-1804
    - name: "Test Kitchen (serverinfo)"
      script:
        - bundle exec kitchen test serverinfo-ubuntu-1804
    - name: "Test Kitchen (spamassassin)"
      script:
        - bundle exec kitchen test spamassassin-ubuntu-1804
    - name: "Test Kitchen (squid)"
      script:
        - bundle exec kitchen test squid-ubuntu-1804
    - name: "Test Kitchen (stateofthemap)"
      script:
        - bundle exec kitchen test stateofthemap-ubuntu-1804
    - name: "Test Kitchen (subversion)"
      script:
        - bundle exec kitchen test subversion-ubuntu-1804
    - name: "Test Kitchen (switch2osm)"
      script:
        - bundle exec kitchen test switch2osm-ubuntu-1804
    - name: "Test Kitchen (taginfo)"
      script:
        - bundle exec kitchen test taginfo-ubuntu-1804
    - name: "Test Kitchen (tilecache)"
      script:
        - bundle exec kitchen test tilecache-ubuntu-1804
    - name: "Test Kitchen (tools)"
      script:
        - bundle exec kitchen test tools-ubuntu-1804
    - name: "Test Kitchen (trac)"
      script:
        - bundle exec kitchen test trac-ubuntu-1804
    - name: "Test Kitchen (web::backend)"
      script:
        - bundle exec kitchen test web-backend-ubuntu-1804
    - name: "Test Kitchen (web::cgimap)"
      script:
        - bundle exec kitchen test web-cgimap-ubuntu-1804
    - name: "Test Kitchen (web::frontend)"
      script:
        - bundle exec kitchen test web-frontend-ubuntu-1804
    - name: "Test Kitchen (web::rails)"
      script:
        - bundle exec kitchen test web-rails-ubuntu-1804
